/**
 * @file    lang.c
 * @brief   UI strings, generated by tools/gen_lang.py - do not edit.
 *          Non-ASCII characters are Windows-1251 codes (see fonts_cyr.c).
 */
#include "lang.h"
#include "settings.h"

static const char * const s_en[S_COUNT] = {
    "",                              /* S_NONE */
    "English",                       /* S_LANG_NAME */
    "On",                            /* S_ON */
    "Off",                           /* S_OFF */
    "Back",                          /* S_BACK */
    "Exit",                          /* S_EXIT */
    "Cancel",                        /* S_CANCEL */
    "Save",                          /* S_SAVE */
    "Click",                         /* S_CLICK */
    "\x7F" "C",                      /* S_U_DEGC */
    "s",                             /* S_U_S */
    "min",                           /* S_U_MIN */
    "ms",                            /* S_U_MS */
    "%",                             /* S_U_PCT */
    "W",                             /* S_U_W */
    "R",                             /* S_U_OHM */
    "V",                             /* S_U_V */
    "Settings",                      /* S_SETTINGS */
    "Tip: %s",                       /* S_TIP_TITLE_FMT */
    "Temperature",                   /* S_TEMPERATURE */
    "Sleep",                         /* S_SLEEP */
    "Clock",                         /* S_CLOCK */
    "Set time",                      /* S_SET_TIME */
    "Display",                       /* S_DISPLAY */
    "System",                        /* S_SYSTEM */
    "Tip",                           /* S_TIP */
    "Tip settings",                  /* S_TIP_SETTINGS */
    "Add new tip",                   /* S_ADD_TIP */
    "Sound",                         /* S_SOUND */
    "Language",                      /* S_LANGUAGE */
    "Name",                          /* S_NAME */
    "Calibrate",                     /* S_CALIBRATE */
    "PID Kp",                        /* S_PID_KP */
    "PID Ki",                        /* S_PID_KI */
    "PID Kd",                        /* S_PID_KD */
    "Reset calib.",                  /* S_RESET_CAL */
    "Delete tip",                    /* S_DELETE_TIP */
    "Min temp",                      /* S_MIN_TEMP */
    "Max temp",                      /* S_MAX_TEMP */
    "Temp step",                     /* S_TEMP_STEP */
    "Boost temp",                    /* S_BOOST_TEMP */
    "Boost time",                    /* S_BOOST_TIME */
    "Motion sensor",                 /* S_MOTION */
    "Sleep after",                   /* S_SLEEP_AFTER */
    "Sleep temp",                    /* S_SLEEP_TEMP */
    "Off after",                     /* S_OFF_AFTER */
    "Enc. wakes",                    /* S_ENC_WAKES */
    "Power on",                      /* S_POWER_ON */
    "Heat",                          /* S_HEAT_OPT */
    "Show clock",                    /* S_SHOW_CLOCK */
    "Format",                        /* S_FORMAT */
    "12h",                           /* S_12H */
    "24h",                           /* S_24H */
    "Clock time",                    /* S_CLOCK_TIME */
    "Setpt time",                    /* S_SETPT_TIME */
    "Hours",                         /* S_HOURS */
    "Minutes",                       /* S_MINUTES */
    "Day",                           /* S_DAY */
    "Month",                         /* S_MONTH */
    "Year",                          /* S_YEAR */
    "Contrast",                      /* S_CONTRAST */
    "Flip 180\x7F",                  /* S_FLIP */
    "Dim idle",                      /* S_DIM_IDLE */
    "PWM period",                    /* S_PWM_PERIOD */
    "ADC delay",                     /* S_ADC_DELAY */
    "Power limit",                   /* S_POWER_LIMIT */
    "Heater R",                      /* S_HEATER_R */
    "Low voltage",                   /* S_LOW_VOLT */
    "TC offset",                     /* S_TC_OFFSET */
    "Encoder",                       /* S_ENCODER */
    "Normal",                        /* S_NORMAL */
    "Reverse",                       /* S_REVERSE */
    "Info",                          /* S_INFO */
    "Factory reset",                 /* S_FACTORY */
    "Reset calibration?",            /* S_RESET_CAL_Q */
    "Cannot delete",                 /* S_CANNOT_DELETE */
    "the last tip",                  /* S_LAST_TIP */
    "Delete this tip?",              /* S_DELETE_TIP_Q */
    "Time saved",                    /* S_TIME_SAVED */
    "Defaults",                      /* S_DEFAULTS */
    "loaded",                        /* S_LOADED */
    "Factory reset?",                /* S_FACTORY_Q */
    "Tip list",                      /* S_TIP_LIST */
    "is full",                       /* S_IS_FULL */
    "OFF",                           /* S_ST_OFF */
    "AUTO OFF",                      /* S_ST_AUTO_OFF */
    "READY",                         /* S_ST_READY */
    "HEAT",                          /* S_ST_HEAT */
    "BOOST %lus",                    /* S_ST_BOOST_FMT */
    "SLEEP zZ",                      /* S_ST_SLEEP */
    "CAL",                           /* S_ST_CAL */
    "SET",                           /* S_SET */
    "No tip",                        /* S_NO_TIP */
    "HOT!",                          /* S_HOT */
    "Tip %d\x7F" "C",                /* S_TIP_FMT */
    "Set %u\x7F" "C",                /* S_SET_FMT */
    "Sleep %u\x7F" "C",              /* S_SLEEP_FMT */
    "%sV",                           /* S_V_FMT */
    "%dW %sV",                       /* S_W_V_FMT */
    "OFF  Set %u\x7F",               /* S_OFF_SET_FMT */
    "Mon",                           /* S_MON */
    "Tue",                           /* S_TUE */
    "Wed",                           /* S_WED */
    "Thu",                           /* S_THU */
    "Fri",                           /* S_FRI */
    "Sat",                           /* S_SAT */
    "Sun",                           /* S_SUN */
    "OVERHEAT",                      /* S_ERR_OVERHEAT */
    "RUNAWAY",                       /* S_ERR_RUNAWAY */
    "NO TIP",                        /* S_ERR_NO_TIP */
    "LOW VOLT",                      /* S_ERR_LOW_VOLT */
    "Click to reset",                /* S_HINT_RESET */
    "Check heater. Click",           /* S_HINT_HEATER */
    "Insert tip / handle",           /* S_HINT_TIP */
    "Vin %sV",                       /* S_HINT_VIN_FMT */
    "Calibration",                   /* S_CALIBRATION */
    "Calibration %u/%u",             /* S_CAL_STEP_FMT */
    "DONE",                          /* S_DONE */
    "FAILED",                        /* S_FAILED */
    "Saved to tip profile",          /* S_CAL_SAVED */
    "Values not monotonic",          /* S_CAL_BAD */
    "Click to exit",                 /* S_CLICK_EXIT */
    "Target %u\x7F" "C",             /* S_TARGET_FMT */
    "Heating...",                    /* S_HEATING */
    "Settling..",                    /* S_SETTLING */
    "Click:skip",                    /* S_CLICK_SKIP */
    "Real tip temp:",                /* S_REAL_TEMP */
    "Click=OK",                      /* S_CLICK_OK */
    "Hold=abort",                    /* S_HOLD_ABORT */
    "Vin %sV  %sW",                  /* S_INFO_VIN_FMT */
    "Tip %d\x7F" "C  ADC %d",        /* S_INFO_TIP_FMT */
    "CJ %s  MCU %s\x7F" "C",         /* S_INFO_CJ_FMT */
    "Duty %d.%d%%  Err %02X",        /* S_INFO_DUTY_FMT */
    "Saves %lu  Moves %lu",          /* S_INFO_SAVES_FMT */
    "Confirm",                       /* S_CONFIRM */
    "Click = Yes",                   /* S_CLICK_YES */
    "Hold  = No ",                   /* S_HOLD_NO */
    "SOLDERING STATION",             /* S_STATION */
    "defaults loaded",               /* S_DEFAULTS_LOADED */
};

static const char * const s_ru[S_COUNT] = {
    "",                              /* S_NONE */
    "\xD0\xF3\xF1\xF1\xEA\xE8\xE9",  /* S_LANG_NAME */
    "\xC2\xEA\xEB",                  /* S_ON */
    "\xC2\xFB\xEA\xEB",              /* S_OFF */
    "\xCD\xE0\xE7\xE0\xE4",          /* S_BACK */
    "\xC2\xFB\xF5\xEE\xE4",          /* S_EXIT */
    "\xCE\xF2\xEC\xE5\xED\xE0",      /* S_CANCEL */
    "\xD1\xEE\xF5\xF0\xE0\xED\xE8\xF2\xFC", /* S_SAVE */
    "\xCD\xE0\xE6\xEC\xE8\xF2\xE5",  /* S_CLICK */
    "\x7F" "C",                      /* S_U_DEGC */
    "\xF1",                          /* S_U_S */
    "\xEC\xE8\xED",                  /* S_U_MIN */
    "\xEC\xF1",                      /* S_U_MS */
    "%",                             /* S_U_PCT */
    "\xC2\xF2",                      /* S_U_W */
    "\xCE\xEC",                      /* S_U_OHM */
    "\xC2",                          /* S_U_V */
    "\xCD\xE0\xF1\xF2\xF0\xEE\xE9\xEA\xE8", /* S_SETTINGS */
    "\xC6\xE0\xEB\xEE: %s",          /* S_TIP_TITLE_FMT */
    "\xD2\xE5\xEC\xEF\xE5\xF0\xE0\xF2\xF3\xF0\xE0", /* S_TEMPERATURE */
    "\xD1\xEE\xED",                  /* S_SLEEP */
    "\xD7\xE0\xF1\xFB",              /* S_CLOCK */
    "\xC7\xE0\xE4\xE0\xF2\xFC \xE2\xF0\xE5\xEC\xFF", /* S_SET_TIME */
    "\xC4\xE8\xF1\xEF\xEB\xE5\xE9",  /* S_DISPLAY */
    "\xD1\xE8\xF1\xF2\xE5\xEC\xE0",  /* S_SYSTEM */
    "\xC6\xE0\xEB\xEE",              /* S_TIP */
    "\xCD\xE0\xF1\xF2\xF0\xEE\xE9\xEA\xE8 \xE6\xE0\xEB\xE0", /* S_TIP_SETTINGS */
    "\xC4\xEE\xE1\xE0\xE2\xE8\xF2\xFC \xE6\xE0\xEB\xEE", /* S_ADD_TIP */
    "\xC7\xE2\xF3\xEA",              /* S_SOUND */
    "\xDF\xE7\xFB\xEA",              /* S_LANGUAGE */
    "\xC8\xEC\xFF",                  /* S_NAME */
    "\xCA\xE0\xEB\xE8\xE1\xF0\xEE\xE2\xEA\xE0", /* S_CALIBRATE */
    "\xCF\xC8\xC4 Kp",               /* S_PID_KP */
    "\xCF\xC8\xC4 Ki",               /* S_PID_KI */
    "\xCF\xC8\xC4 Kd",               /* S_PID_KD */
    "\xD1\xE1\xF0\xEE\xF1 \xEA\xE0\xEB\xE8\xE1\xF0.", /* S_RESET_CAL */
    "\xD3\xE4\xE0\xEB\xE8\xF2\xFC \xE6\xE0\xEB\xEE", /* S_DELETE_TIP */
    "\xCC\xE8\xED. \xF2\xE5\xEC\xEF.", /* S_MIN_TEMP */
    "\xCC\xE0\xEA\xF1. \xF2\xE5\xEC\xEF.", /* S_MAX_TEMP */
    "\xD8\xE0\xE3 \xF2\xE5\xEC\xEF.", /* S_TEMP_STEP */
    "\xD4\xEE\xF0\xF1\xE0\xE6 \xF2\xE5\xEC\xEF.", /* S_BOOST_TEMP */
    "\xD4\xEE\xF0\xF1\xE0\xE6 \xE2\xF0\xE5\xEC\xFF", /* S_BOOST_TIME */
    "\xC4\xE0\xF2\xF7\xE8\xEA \xE2\xE8\xE1\xF0.", /* S_MOTION */
    "\xD1\xEE\xED \xF7\xE5\xF0\xE5\xE7", /* S_SLEEP_AFTER */
    "\xD2\xE5\xEC\xEF. \xF1\xED\xE0", /* S_SLEEP_TEMP */
    "\xC2\xFB\xEA\xEB. \xF7\xE5\xF0\xE5\xE7", /* S_OFF_AFTER */
    "\xDD\xED\xEA\xEE\xE4\xE5\xF0 \xE1\xF3\xE4\xE8\xF2", /* S_ENC_WAKES */
    "\xCF\xF0\xE8 \xE2\xEA\xEB\xFE\xF7.", /* S_POWER_ON */
    "\xCD\xE0\xE3\xF0\xE5\xE2",      /* S_HEAT_OPT */
    "\xCF\xEE\xEA\xE0\xE7 \xF7\xE0\xF1\xEE\xE2", /* S_SHOW_CLOCK */
    "\xD4\xEE\xF0\xEC\xE0\xF2",      /* S_FORMAT */
    "12\xF7",                        /* S_12H */
    "24\xF7",                        /* S_24H */
    "\xC2\xF0\xE5\xEC\xFF \xF7\xE0\xF1\xEE\xE2", /* S_CLOCK_TIME */
    "\xC2\xF0\xE5\xEC\xFF \xF3\xF1\xF2\xE0\xE2\xEA\xE8", /* S_SETPT_TIME */
    "\xD7\xE0\xF1\xFB",              /* S_HOURS */
    "\xCC\xE8\xED\xF3\xF2\xFB",      /* S_MINUTES */
    "\xC4\xE5\xED\xFC",              /* S_DAY */
    "\xCC\xE5\xF1\xFF\xF6",          /* S_MONTH */
    "\xC3\xEE\xE4",                  /* S_YEAR */
    "\xCA\xEE\xED\xF2\xF0\xE0\xF1\xF2", /* S_CONTRAST */
    "\xCF\xEE\xE2\xEE\xF0\xEE\xF2 180\x7F", /* S_FLIP */
    "\xC7\xE0\xF2\xE5\xEC\xED\xE5\xED\xE8\xE5", /* S_DIM_IDLE */
    "\xCF\xE5\xF0\xE8\xEE\xE4 \xD8\xC8\xCC", /* S_PWM_PERIOD */
    "\xC7\xE0\xE4\xE5\xF0\xE6\xEA\xE0 \xC0\xD6\xCF", /* S_ADC_DELAY */
    "\xCE\xE3\xF0. \xEC\xEE\xF9\xED\xEE\xF1\xF2\xE8", /* S_POWER_LIMIT */
    "R \xED\xE0\xE3\xF0\xE5\xE2\xE0\xF2\xE5\xEB\xFF", /* S_HEATER_R */
    "\xCC\xE8\xED. \xED\xE0\xEF\xF0\xFF\xE6.", /* S_LOW_VOLT */
    "\xD1\xEC\xE5\xF9\xE5\xED\xE8\xE5 \xD2\xCF", /* S_TC_OFFSET */
    "\xDD\xED\xEA\xEE\xE4\xE5\xF0",  /* S_ENCODER */
    "\xCF\xF0\xFF\xEC\xEE\xE5",      /* S_NORMAL */
    "\xCE\xE1\xF0\xE0\xF2\xED\xEE\xE5", /* S_REVERSE */
    "\xC8\xED\xF4\xEE",              /* S_INFO */
    "\xD1\xE1\xF0\xEE\xF1 \xED\xE0\xF1\xF2\xF0\xEE\xE5\xEA", /* S_FACTORY */
    "\xD1\xE1\xF0\xEE\xF1\xE8\xF2\xFC \xEA\xE0\xEB\xE8\xE1\xF0\xEE\xE2\xEA\xF3?", /* S_RESET_CAL_Q */
    "\xCD\xE5\xEB\xFC\xE7\xFF \xF3\xE4\xE0\xEB\xE8\xF2\xFC", /* S_CANNOT_DELETE */
    "\xEF\xEE\xF1\xEB\xE5\xE4\xED\xE5\xE5 \xE6\xE0\xEB\xEE", /* S_LAST_TIP */
    "\xD3\xE4\xE0\xEB\xE8\xF2\xFC \xFD\xF2\xEE \xE6\xE0\xEB\xEE?", /* S_DELETE_TIP_Q */
    "\xC2\xF0\xE5\xEC\xFF \xF1\xEE\xF5\xF0\xE0\xED\xE5\xED\xEE", /* S_TIME_SAVED */
    "\xCD\xE0\xF1\xF2\xF0\xEE\xE9\xEA\xE8", /* S_DEFAULTS */
    "\xF1\xE1\xF0\xEE\xF8\xE5\xED\xFB", /* S_LOADED */
    "\xD1\xE1\xF0\xEE\xF1\xE8\xF2\xFC \xED\xE0\xF1\xF2\xF0\xEE\xE9\xEA\xE8?", /* S_FACTORY_Q */
    "\xD1\xEF\xE8\xF1\xEE\xEA \xE6\xE0\xEB", /* S_TIP_LIST */
    "\xE7\xE0\xEF\xEE\xEB\xED\xE5\xED", /* S_IS_FULL */
    "\xC2\xDB\xCA\xCB",              /* S_ST_OFF */
    "\xC0\xC2\xD2\xCE\xC2\xDB\xCA\xCB", /* S_ST_AUTO_OFF */
    "\xC3\xCE\xD2\xCE\xC2",          /* S_ST_READY */
    "\xCD\xC0\xC3\xD0\xC5\xC2",      /* S_ST_HEAT */
    "\xD4\xCE\xD0\xD1\xC0\xC6 %lu\xF1", /* S_ST_BOOST_FMT */
    "\xD1\xCE\xCD zZ",               /* S_ST_SLEEP */
    "\xCA\xC0\xCB",                  /* S_ST_CAL */
    "\xD3\xD1\xD2",                  /* S_SET */
    "\xCD\xE5\xF2 \xE6\xE0\xEB\xE0", /* S_NO_TIP */
    "\xC3\xCE\xD0\xDF\xD7\xCE!",     /* S_HOT */
    "\xC6\xE0\xEB\xEE %d\x7F" "C",   /* S_TIP_FMT */
    "\xD3\xF1\xF2 %u\x7F" "C",       /* S_SET_FMT */
    "\xD1\xEE\xED %u\x7F" "C",       /* S_SLEEP_FMT */
    "%s\xC2",                        /* S_V_FMT */
    "%d\xC2\xF2 %s\xC2",             /* S_W_V_FMT */
    "\xC2\xDB\xCA\xCB  \xD3\xF1\xF2 %u\x7F", /* S_OFF_SET_FMT */
    "\xCF\xED",                      /* S_MON */
    "\xC2\xF2",                      /* S_TUE */
    "\xD1\xF0",                      /* S_WED */
    "\xD7\xF2",                      /* S_THU */
    "\xCF\xF2",                      /* S_FRI */
    "\xD1\xE1",                      /* S_SAT */
    "\xC2\xF1",                      /* S_SUN */
    "\xCF\xC5\xD0\xC5\xC3\xD0\xC5\xC2", /* S_ERR_OVERHEAT */
    "\xCE\xD2\xCA\xC0\xC7",          /* S_ERR_RUNAWAY */
    "\xCD\xC5\xD2 \xC6\xC0\xCB\xC0", /* S_ERR_NO_TIP */
    "\xCD\xC8\xC7\xCA\xCE\xC5 U",    /* S_ERR_LOW_VOLT */
    "\xCD\xE0\xE6\xEC\xE8\xF2\xE5 \xE4\xEB\xFF \xF1\xE1\xF0\xEE\xF1\xE0", /* S_HINT_RESET */
    "\xCF\xF0\xEE\xE2\xE5\xF0\xFC\xF2\xE5 \xED\xE0\xE3\xF0\xE5\xE2", /* S_HINT_HEATER */
    "\xC2\xF1\xF2\xE0\xE2\xFC\xF2\xE5 \xE6\xE0\xEB\xEE", /* S_HINT_TIP */
    "U\xE2\xF5 %s\xC2",              /* S_HINT_VIN_FMT */
    "\xCA\xE0\xEB\xE8\xE1\xF0\xEE\xE2\xEA\xE0", /* S_CALIBRATION */
    "\xCA\xE0\xEB\xE8\xE1\xF0\xEE\xE2\xEA\xE0 %u/%u", /* S_CAL_STEP_FMT */
    "\xC3\xCE\xD2\xCE\xC2\xCE",      /* S_DONE */
    "\xCE\xD8\xC8\xC1\xCA\xC0",      /* S_FAILED */
    "\xD1\xEE\xF5\xF0\xE0\xED\xE5\xED\xEE \xE2 \xEF\xF0\xEE\xF4\xE8\xEB\xFC", /* S_CAL_SAVED */
    "\xC7\xED\xE0\xF7\xE5\xED\xE8\xFF \xED\xE5 \xF0\xE0\xF1\xF2\xF3\xF2", /* S_CAL_BAD */
    "\xCD\xE0\xE6\xEC\xE8\xF2\xE5 \xE4\xEB\xFF \xE2\xFB\xF5\xEE\xE4\xE0", /* S_CLICK_EXIT */
    "\xD6\xE5\xEB\xFC %u\x7F" "C",   /* S_TARGET_FMT */
    "\xCD\xE0\xE3\xF0\xE5\xE2...",   /* S_HEATING */
    "\xCE\xE6\xE8\xE4\xE0\xED\xE8\xE5..", /* S_SETTLING */
    "\xCA\xEB\xE8\xEA:\xE4\xE0\xEB\xE5\xE5", /* S_CLICK_SKIP */
    "\xD0\xE5\xE0\xEB\xFC\xED\xE0\xFF \xF2\xE5\xEC\xEF.:", /* S_REAL_TEMP */
    "\xCA\xEB\xE8\xEA=OK",           /* S_CLICK_OK */
    "\xD3\xE4\xE5\xF0\xE6=\xEE\xF2\xEC\xE5\xED\xE0", /* S_HOLD_ABORT */
    "U\xE2\xF5 %s\xC2  %s\xC2\xF2",  /* S_INFO_VIN_FMT */
    "\xC6\xE0\xEB\xEE %d\x7F" "C  \xC0\xD6\xCF %d", /* S_INFO_TIP_FMT */
    "\xD5\xD1 %s  \xCC\xCA %s\x7F" "C", /* S_INFO_CJ_FMT */
    "\xD8\xC8\xCC %d.%d%%  \xCE\xF8 %02X", /* S_INFO_DUTY_FMT */
    "\xC7\xE0\xEF\xE8\xF1\xE5\xE9 %lu  \xC4\xE2 %lu", /* S_INFO_SAVES_FMT */
    "\xCF\xEE\xE4\xF2\xE2\xE5\xF0\xE6\xE4\xE5\xED\xE8\xE5", /* S_CONFIRM */
    "\xCA\xEB\xE8\xEA  = \xC4\xE0 ", /* S_CLICK_YES */
    "\xD3\xE4\xE5\xF0\xE6 = \xCD\xE5\xF2", /* S_HOLD_NO */
    "\xCF\xC0\xDF\xCB\xDC\xCD\xC0\xDF \xD1\xD2\xC0\xCD\xD6\xC8\xDF", /* S_STATION */
    "\xED\xE0\xF1\xF2\xF0\xEE\xE9\xEA\xE8 \xF1\xE1\xF0\xEE\xF8\xE5\xED\xFB", /* S_DEFAULTS_LOADED */
};

static const char * const * const s_tables[LANG_COUNT] = {
    s_en, s_ru
};

const char *tr(str_id_t id)
{
    uint8_t lang = g_set.lang < (uint8_t)LANG_COUNT ? g_set.lang : (uint8_t)LANG_EN;
    if ((unsigned)id >= (unsigned)S_COUNT) return "";
    return s_tables[lang][id];
}

const char *lang_name(uint8_t lang)
{
    if (lang >= (uint8_t)LANG_COUNT) lang = (uint8_t)LANG_EN;
    return s_tables[lang][S_LANG_NAME];
}
