#!/usr/bin/env python3
"""
Generates Core/Src/fonts_digits.c - large digit fonts for the OLED.

Glyphs are rendered from DejaVu Sans Mono Bold (Bitstream Vera license,
bitmaps derived from it may be used freely) and stored column-major,
LSB = top pixel, ceil(height/8) bytes per column.

Usage:  pip install pillow
        python3 tools/gen_fonts.py [path/to/DejaVuSansMono-Bold.ttf] [--preview]
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

ARGS = [a for a in sys.argv[1:] if not a.startswith("--")]
FONT_PATH = ARGS[0] if ARGS else "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf"
OUT = os.path.join(os.path.dirname(__file__), "..", "Core", "Src", "fonts_digits.c")

# name, point size, glyph height, characters
FONTS = [
    ("font_mid", 22, 16, "0123456789:-. "),
    ("font_big", 42, 32, "0123456789:- "),
]


def render(size, height, chars):
    font = ImageFont.truetype(FONT_PATH, size)
    digits = "0123456789"
    top = min(font.getbbox(c)[1] for c in digits)
    bottom = max(font.getbbox(c)[3] for c in digits)
    # center the digit body vertically in the glyph box
    y0 = top - ((height - (bottom - top)) // 2)
    adv = int(round(font.getlength("0")))
    left = min(font.getbbox(c)[0] for c in digits)
    right = max(font.getbbox(c)[2] for c in digits)
    digit_w = right - left

    glyphs = []
    for ch in chars:
        img = Image.new("L", (adv * 2, height), 0)
        d = ImageDraw.Draw(img)
        d.text((-left, -y0), ch, font=font, fill=255)
        px = img.load()
        if ch in digits or ch == " ":
            x0, x1 = 0, digit_w
        else:
            cols = [x for x in range(img.width) if any(px[x, y] > 127 for y in range(height))]
            x0, x1 = (cols[0], cols[-1] + 1) if cols else (0, digit_w // 2)
            x0, x1 = max(0, x0 - 1), x1 + 1
        if ch == " ":
            cols_data = [[0] * height for _ in range(digit_w)]
        else:
            cols_data = [[1 if px[x, y] > 127 else 0 for y in range(height)] for x in range(x0, x1)]
        glyphs.append((ch, cols_data))
    return glyphs


def encode(cols, height):
    pages = (height + 7) // 8
    out = []
    for col in cols:
        for p in range(pages):
            b = 0
            for bit in range(8):
                y = p * 8 + bit
                if y < height and col[y]:
                    b |= 1 << bit
            out.append(b)
    return out


def preview(ch, cols, height):
    lines = []
    for y in range(height):
        lines.append("".join("#" if c[y] else "." for c in cols))
    return lines


def main():
    src = []
    src.append("/**\n * @file    fonts_digits.c\n * @brief   Large digit fonts, generated by tools/gen_fonts.py - do not edit.\n"
               " *          Source: DejaVu Sans Mono Bold (Bitstream Vera license).\n */")
    src.append('#include "fonts.h"\n')
    for name, size, height, chars in FONTS:
        glyphs = render(size, height, chars)
        data, offsets, widths = [], [], []
        for ch, cols in glyphs:
            offsets.append(len(data))
            widths.append(len(cols))
            data.extend(encode(cols, height))
        src.append(f"static const uint8_t {name}_data[{len(data)}] = {{")
        pos = 0
        for (ch, cols), w, off in zip(glyphs, widths, offsets):
            n = w * ((height + 7) // 8)
            chunk = data[off:off + n]
            src.append(f"    /* '{ch}' */")
            for i in range(0, len(chunk), 16):
                src.append("    " + ", ".join(f"0x{b:02X}" for b in chunk[i:i + 16]) + ",")
            pos += n
        src.append("};\n")
        src.append(f"static const uint8_t {name}_widths[{len(widths)}] = {{ " + ", ".join(map(str, widths)) + " };")
        src.append(f"static const uint16_t {name}_offsets[{len(offsets)}] = {{ " + ", ".join(map(str, offsets)) + " };\n")
        src.append(f"const font_t {name} = {{\n    {height}U, 2U, 0U, {len(chars)}U, \"{chars}\", 0U,\n"
                   f"    {name}_widths, {name}_offsets, {name}_data, 0\n}};\n")
        if "--preview" in sys.argv:
            for ch, cols in glyphs:
                print(f"{name} '{ch}'")
                print("\n".join(preview(ch, cols, height)))
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(src))
    print("written", os.path.abspath(OUT))


if __name__ == "__main__":
    main()
